cmake_minimum_required(VERSION 3.20)
project(crypto-market-data-aggregator LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(OpenSSL REQUIRED)

# Alternative in case of issues to install dependencies
set(USE_FETCH_CONTENT OFF)

if(USE_FETCH_CONTENT)
    message(STATUS "Will use FetchContent and build all dependencies!")
    list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
    include(FetchContent)
    include(boost)
    include(catch2)
    include(grpc)
    include(json)
else()
    message(STATUS "Will not use FetchContent but rely on installed dependencies.")
    find_package(Threads REQUIRED)
    find_package(nlohmann_json REQUIRED)
    find_package(Boost REQUIRED COMPONENTS system)
    find_package(Protobuf REQUIRED)
    find_package(gRPC REQUIRED)
    find_package(Catch2 3 QUIET)
    if(NOT Catch2_FOUND)
        message(STATUS "Catch2 v3 was not found. Trying to fallback to v2.")
        find_package(Catch2 REQUIRED)
    endif()
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    if(SAN_MODE STREQUAL "ASAN")
        message(STATUS "ASan mode will check for undefined behavior.")
        add_compile_options(-fsanitize=address -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address -fno-omit-frame-pointer)
    elseif(SAN_MODE STREQUAL "UBSAN")
        message(STATUS "UBSan mode will check for undefined behavior.")
        add_compile_options(-fsanitize=undefined -fno-omit-frame-pointer)
        add_link_options(-fsanitize=undefined -fno-omit-frame-pointer)
    elseif(SAN_MODE STREQUAL "TSAN")
        message(STATUS "TSan mode will check for data races and synchronization issues.")
        add_compile_options(-fsanitize=thread -Wno-tsan -O1)
        add_link_options(-fsanitize=thread -O1)
    elseif(SAN_MODE STREQUAL "LSAN")
        message(STATUS "LSan mode will check for memory leaks.")
        add_compile_options(-fsanitize=leak)
        add_link_options(-fsanitize=leak)
    endif()
endif()

add_compile_options(-Wall -Wextra -Wfatal-errors -fmax-errors=1)

enable_testing()

add_subdirectory(proto)
add_subdirectory(src)
add_subdirectory(test)
